### ISSUE TITLE
`dc build` failed on `RUN pip3 install pymacaroons pytest`

### ISSUE THREAD

**Issue by cmbankester** [ecordell/macaroon-compatibility#1]
The trace:

```
Step 18 : RUN pip3 install pymacaroons pytest
 ---> Running in aa18860e927a
Downloading/unpacking pymacaroons
  Downloading pymacaroons-0.8.0-py2.py3-none-any.whl
Downloading/unpacking pytest
Downloading/unpacking libnacl>=1.3.6 (from pymacaroons)
  Downloading libnacl-1.4.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/libnacl/setup.py) egg_info for package libnacl

Downloading/unpacking six>=1.8.0 (from pymacaroons)
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking py>=1.4.25 (from pytest)
Installing collected packages: pymacaroons, pytest, libnacl, six, py
  Running setup.py install for libnacl

  Found existing installation: six 1.5.2
    Uninstalling six:
      Successfully uninstalled six
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1443, in install
    requirement.commit_uninstall()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 610, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1860, in commit
    rmtree(self.save_dir)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 43, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python3.4/shutil.py", line 463, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.4/shutil.py", line 401, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.4/shutil.py", line 401, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.4/shutil.py", line 401, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.4/shutil.py", line 405, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.4/shutil.py", line 403, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'dist-packages'

Storing debug log for failure in /root/.pip/pip.log
Service 'test' failed to build: The command [/bin/sh -c pip3 install pymacaroons pytest] returned a non-zero code: 2
```

**Comment by ecordell** [comment]
I _think_ this is a bug with the filesystem sharing in dinghy/boot2docker. If you're using one, try switching to the other?

Found a couple of other references to this problem: https://github.com/hashdist/hashdist/issues/113 and it looks related to NFS

**Comment by cmbankester** [comment]
I'm not using dinghy (or NFS for that matter). This is on coreos-alpha running via Vagrant on Mac OSX with no mounting from OSX into the CoreOS node.

Christian Bankester
cbankester@immense.netmailto:cbankester@immense.net

On Fri, May 22, 2015 at 10:19 AM -0700, "Evan Cordell" <notifications@github.com<mailto:notifications@github.com>> wrote:

I think this is a bug with the filesystem sharing in dinghy/boot2docker. If you're using one, try switching to the other?

Found a couple of other references to this problem: hashdist/hashdist#113https://github.com/hashdist/hashdist/issues/113 and it looks related to NFS

##
